### ISSUE TITLE
MVVM Listbox

### ISSUE THREAD

**Issue by OceanOSdev** [MTN-Software/French#1]
The listbox in the xaml (both for windows and windows phone) is not correctly binded to the VerbViewModel.

**Comment by Zoinkster1** [comment]
So fix it. Duh

**Comment by OceanOSdev** [comment]
If I could just fix it, then I wouldn't have posted the "help wanted"...

**Comment by Zoinkster1** [comment]
Pleb

**Comment by Zoinkster1** [comment]
Dammit Tj just leave it open or closed. Make up your mind!
